### ISSUE TITLE
*Extremely severe* slowdown when visiting http://asa.org.il/

### ISSUE THREAD

**Issue by SafwatHalaby** [adblockplus/adblockplus#1]
When visiting http://asa.org.il/ with Adblock Plus, the filtering counter skyrockets into millions, Adblock Plus "blocks" millions of stuff per second. CPU and hard drive IO are utilized maximally, and the entire system slows down. One of the tests even managed to crash Firefox. Closing http://asa.org.il/ instantly re-stablizes the system.

Tested in Chrome and Firefox.
Versions:
```
OS: Debian Jessie
Firefox: 38.3.0 (Iceweasel Branding), with Adblock Plus V2.6.11
Chromium: Version 45.0.2454.85 Built on 8.1, running on Debian 8.2 (64-bit), with Adblock Plus V1.9.3
```

**Comment by mapx-** [comment]
see
https://adblockplus.org/forum/viewtopic.php?p=141086#p141086
